"""empty message

Revision ID: 526b73c27217
Revises: ef22ee768cb8
Create Date: 2024-06-03 17:51:58.561010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b73c27217'
down_revision = 'ef22ee768cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('home_world',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('vehicles',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('characters_films_fkey', type_='foreignkey')
        batch_op.drop_constraint('characters_vehicles_fkey', type_='foreignkey')
        batch_op.drop_constraint('characters_home_world_fkey', type_='foreignkey')

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('characters',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('planets',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('vehicles',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('films_planets_fkey', type_='foreignkey')
        batch_op.drop_constraint('films_characters_fkey', type_='foreignkey')
        batch_op.drop_constraint('films_vehicles_fkey', type_='foreignkey')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('residents',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('planets_residents_fkey', type_='foreignkey')
        batch_op.drop_constraint('planets_films_fkey', type_='foreignkey')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('films',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('vehicles_films_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_foreign_key('vehicles_films_fkey', 'films', ['films'], ['id'])
        batch_op.alter_column('films',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_foreign_key('planets_films_fkey', 'films', ['films'], ['id'])
        batch_op.create_foreign_key('planets_residents_fkey', 'characters', ['residents'], ['id'])
        batch_op.alter_column('films',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('residents',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.create_foreign_key('films_vehicles_fkey', 'vehicles', ['vehicles'], ['id'])
        batch_op.create_foreign_key('films_characters_fkey', 'characters', ['characters'], ['id'])
        batch_op.create_foreign_key('films_planets_fkey', 'planets', ['planets'], ['id'])
        batch_op.alter_column('vehicles',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('planets',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('characters',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_foreign_key('characters_home_world_fkey', 'planets', ['home_world'], ['id'])
        batch_op.create_foreign_key('characters_vehicles_fkey', 'vehicles', ['vehicles'], ['id'])
        batch_op.create_foreign_key('characters_films_fkey', 'films', ['films'], ['id'])
        batch_op.alter_column('vehicles',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('home_world',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
