"""empty message

Revision ID: 7440755b4049
Revises: 3a09bc3e6a68
Create Date: 2024-06-03 17:43:36.693396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7440755b4049'
down_revision = '3a09bc3e6a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('opening_crawl', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('characters', sa.Integer(), nullable=True),
    sa.Column('planets', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opening_crawl'),
    sa.UniqueConstraint('release_date'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'films', ['films'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'films', ['films'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('films')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('films')

    op.drop_table('films')
    # ### end Alembic commands ###
