"""empty message

Revision ID: ef22ee768cb8
Revises: 7440755b4049
Create Date: 2024-06-03 17:45:56.509011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef22ee768cb8'
down_revision = '7440755b4049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Float(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('passengers', sa.Float(), nullable=True),
    sa.Column('cargo_capacity', sa.Float(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('pilots', sa.String(), nullable=True),
    sa.Column('films', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['films'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles'], ['id'])

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles')

    op.drop_table('vehicles')
    # ### end Alembic commands ###
